"""
Local-only Nuitka experiment builder for critical security/license modules.

This does not replace the production PyInstaller flow. It compiles only a few
custom modules to extension modules (.pyd) and places them in an overlay tree
under .nuitka_critical so they can be tested safely without touching the
source package.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent
OVERLAY_ROOT = REPO_ROOT / ".nuitka_critical"
TEMP_ROOT = REPO_ROOT / "build" / "nuitka_module_build"
REPORT_ROOT = REPO_ROOT / "build" / "nuitka_reports"


@dataclass(frozen=True)
class TargetModule:
    source: str
    import_name: str

    @property
    def source_path(self) -> Path:
        return REPO_ROOT / self.source

    @property
    def package_parts(self) -> list[str]:
        return self.import_name.split(".")[:-1]


TARGETS = [
    TargetModule("modules/license/hardware_id.py", "modules.license.hardware_id"),
    TargetModule("modules/license/firebase_license_manager.py", "modules.license.firebase_license_manager"),
    TargetModule("modules/license/license_manager.py", "modules.license.license_manager"),
    TargetModule("modules/license/creator_links_tracking.py", "modules.license.creator_links_tracking"),
    TargetModule("modules/license/lease_crypto.py", "modules.license.lease_crypto"),
    TargetModule("modules/security/hardening.py", "modules.security.hardening"),
]


def _run(command: list[str]) -> None:
    print(f"\n> {' '.join(command)}")
    subprocess.run(command, check=True, cwd=str(REPO_ROOT))


def _ensure_nuitka_available() -> None:
    try:
        _run([sys.executable, "-m", "nuitka", "--version"])
    except subprocess.CalledProcessError as exc:
        raise SystemExit(
            "Nuitka is not available in this Python environment. "
            "Install it with: python -m pip install -U nuitka"
        ) from exc


def _clean_previous_output() -> None:
    for path in (OVERLAY_ROOT, TEMP_ROOT, REPORT_ROOT):
        if path.exists():
            shutil.rmtree(path)
    OVERLAY_ROOT.mkdir(parents=True, exist_ok=True)
    TEMP_ROOT.mkdir(parents=True, exist_ok=True)
    REPORT_ROOT.mkdir(parents=True, exist_ok=True)


def _package_rel_dir(package_parts: list[str]) -> Path:
    return Path(*package_parts)


def _write_package_shim(package_parts: list[str]) -> None:
    package_rel_dir = _package_rel_dir(package_parts)
    target_dir = OVERLAY_ROOT / package_rel_dir
    target_dir.mkdir(parents=True, exist_ok=True)

    source_dir = REPO_ROOT / package_rel_dir
    source_init = source_dir / "__init__.py"
    original = source_init.read_text(encoding="utf-8") if source_init.exists() else ""

    shim = textwrap.dedent(
        f"""
        # Auto-generated by build_nuitka_critical.py
        _SOURCE_PACKAGE_DIR = r"{source_dir}"
        if _SOURCE_PACKAGE_DIR not in __path__:
            __path__.append(_SOURCE_PACKAGE_DIR)
        """
    ).lstrip()

    if original.strip():
        shim += "\n" + original + ("\n" if not original.endswith("\n") else "")

    (target_dir / "__init__.py").write_text(shim, encoding="utf-8")


def _prepare_package_shims() -> None:
    all_packages: set[tuple[str, ...]] = set()
    for target in TARGETS:
        parts = target.package_parts
        for index in range(1, len(parts) + 1):
            all_packages.add(tuple(parts[:index]))

    for package_parts in sorted(all_packages, key=len):
        _write_package_shim(list(package_parts))


def _compile_target(target: TargetModule) -> None:
    module_build_dir = TEMP_ROOT / target.import_name.replace(".", "_")
    module_build_dir.mkdir(parents=True, exist_ok=True)

    report_path = REPORT_ROOT / f"{target.import_name.replace('.', '_')}.xml"
    command = [
        sys.executable,
        "-m",
        "nuitka",
        "--mode=module",
        "--zig",
        "--assume-yes-for-downloads",
        "--remove-output",
        "--no-pyi-file",
        f"--output-dir={module_build_dir}",
        f"--report={report_path}",
        str(target.source_path),
    ]
    _run(command)

    candidates = sorted(module_build_dir.glob(f"{target.source_path.stem}*.pyd"))
    if not candidates:
        raise SystemExit(
            f"Compiled artifact not found for {target.import_name}. "
            f"Expected a .pyd in {module_build_dir}."
        )

    artifact = candidates[0]
    overlay_package_dir = OVERLAY_ROOT / _package_rel_dir(target.package_parts)
    overlay_package_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(artifact, overlay_package_dir / artifact.name)
    print(f"Copied: {artifact.name} -> {overlay_package_dir}")


def _write_manifest() -> None:
    lines = [
        "# Auto-generated Nuitka critical-module overlay",
        "",
        "Compiled modules:",
    ]
    for target in TARGETS:
        lines.append(f"- {target.import_name}")
    lines.extend(
        [
            "",
            "Use launch_nuitka_critical_test.py to run the app with this overlay.",
        ]
    )
    (OVERLAY_ROOT / "README.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    print("Preparing local Nuitka critical-module overlay build...")
    _ensure_nuitka_available()
    _clean_previous_output()
    _prepare_package_shims()

    for target in TARGETS:
        print(f"\n=== Compiling {target.import_name} ===")
        _compile_target(target)

    _write_manifest()

    print("\nDone.")
    print(f"Overlay root : {OVERLAY_ROOT}")
    print(f"Reports      : {REPORT_ROOT}")
    print("Next step    : python launch_nuitka_critical_test.py --probe-only")
    print("Then         : python launch_nuitka_critical_test.py")


if __name__ == "__main__":
    main()
